name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:


jobs:

  c:
    name: Test C Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SetUp C Env
        run: |
          sudo apt install gcc libsqlite3-dev libjson-c-dev
          cd c
          make prepare
          make build
          nohup make run > server.log 2>&1 &
      - name: SetUp Test env
        run: |
          sudo apt install python python3-pip
          cd tests
          pip3 install -U requests pytest
      - name: Run tests
        run: |
          python3 -m pytest --verbose -s

  go:
    name: Test Go Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SetUp Go Env
        run: |
          mkdir tmp
          cd tmp
          wget https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz
          sudo tar -xvf go1.15.1.linux-amd64.tar.gz\nsudo mv go /usr/local
          export GOROOT=/usr/local/go
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
          cd ../go
          make prepare
          make build
          nohup make run > server.log 2>&1 &
      - name: SetUp Test env
        run: |
          sudo apt install python python3-pip
          cd tests
          pip3 install -U requests pytest
      - name: Run tests
        run: |
          python3 -m pytest --verbose -s

  nodejs:
    name: Test Nodejs Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SetUp Nodejs Env
        run: |
          sudo npm install -g n
          sudo n stable
          cd nodejs
          make prepare
          make build
          nohup make run > server.log 2>&1 &
      - name: SetUp Test env
        run: |
          sudo apt install python python3-pip
          cd tests
          pip3 install -U requests pytest
      - name: Run tests
        run: |
          python3 -m pytest --verbose -s

  php:
    name: Test PHP Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SetUp PHP Env
        run: |
          sudo apt install php php-sqlite3 composer
          cd php
          make prepare
          make build
          nohup make run > server.log 2>&1 &
      - name: SetUp Test env
        run: |
          sudo apt install python python3-pip
          cd tests
          pip3 install -U requests pytest
      - name: Run tests
        run: |
          python3 -m pytest --verbose -s

  python:
    name: Test Python Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SetUp Python Env
        run: |
          sudo apt install python python3-pip
          sudo -H pip3 install virtualenv
          cd python
          make prepare
          make build
          nohup make run > server.log 2>&1 &
      - name: SetUp Test env
        run: |
          sudo apt install python python3-pip
          cd tests
          pip3 install -U requests pytest
      - name: Run tests
        run: |
          python3 -m pytest --verbose -s

  rust:
    name: Test Rust Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SetUp Rust Env
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          cd rust
          rustup update nightly
          rustup default nightly
          make prepare
          make build
          nohup make run > server.log 2>&1 &
      - name: SetUp Test env
        run: |
          sudo apt install python python3-pip
          cd tests
          pip3 install -U requests pytest
      - name: Run tests
        run: |
          python3 -m pytest --verbose -s
