name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:


jobs:

  php:
    name: PHP TaskList
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SetUp PHP Env
        run: |
          sudo apt install php php-sqlite3 composer
          cd php
          make prepare
          make build
          nohup make run > server.log 2>&1 &
      - name: SetUp Test env
        run: |
          sudo apt install python python3-pip
          cd tests
          sudo -H pip3 install virtualenv
          pip3 install -U requests pytest
      - name: Run tests
        run: |
          python3 -m pytest --verbose -s
